# AI Ledger Solutions - Production Version
services:
- name: ai-ledger-solutions
  type: web
  runtime: node
  plan: starter
  buildCommand: npm install
  startCommand: npm start
  envVars:
  - key: NODE_ENV
    value: production
  - key: XRPL_NETWORK
    value: mainnet
  - key: XRPL_WALLET_SEED
    sync: false
  - key: XRPL_WALLET_ADDRESS  
    sync: false
  - key: PORT
    value: 10000

- name: ai-ledger-testnet-dashboard
  type: web
  runtime: node
  plan: starter
  buildCommand: npm install
  startCommand: node simple-testnet-dashboard.js
  envVars:
  - key: NODE_ENV
    value: development
  - key: XRPL_NETWORK
    value: testnet
  - key: PORT
    value: 10000

- name: ai-ledger-mainnet-dashboard
  type: web
  runtime: node
  plan: starter
  buildCommand: npm install
  startCommand: node mainnet-dashboard.js
  envVars:
  - key: NODE_ENV
    value: production
  - key: XRPL_NETWORK
    value: mainnet
  - key: PORT
    value: 10000
