services:
  - type: web
    name: quantum-yield-empire
    runtime: node
    buildCommand: npm install
    startCommand: node professional-website/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    healthCheckPath: /
    autoDeploy: true
    plan: starter
    region: oregon
    branch: master

  - type: web
    name: quantum-dashboard
    runtime: node
    buildCommand: npm install
    startCommand: node simple-testnet-dashboard.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10001
    healthCheckPath: /
    autoDeploy: true
    plan: starter
    region: oregon
    branch: master 