services:
  # Main Quantum Yield Empire - Production Version
  - type: web
    name: quantum-yield-empire
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node quantum-empire-production.js
    envVars:
      - key: NETWORK
        value: mainnet
      - key: NODE_ENV
        value: production
      - key: WALLET_SEED
        sync: false  # Set this in Render dashboard for security
    healthCheckPath: /health

  # Professional Website & Dashboard
  - type: web
    name: quantum-professional-website
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node professional-website/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001

  # Testnet Dashboard for Development
  - type: web
    name: quantum-testnet-dashboard
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node simple-testnet-dashboard.js
    envVars:
      - key: NETWORK
        value: testnet
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3002

  # Mainnet Performance Dashboard
  - type: web
    name: quantum-mainnet-dashboard
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node mainnet-dashboard.js
    envVars:
      - key: NETWORK
        value: mainnet
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3003
      - key: WALLET_SEED
        sync: false  # Set this in Render dashboard for security

  # Background Worker for Beast Mode Bot
  - type: worker
    name: quantum-beast-mode-worker
    runtime: node
    plan: starter
    buildCommand: npm install
    startCommand: node beast-mode-network-launcher.js mainnet
    envVars:
      - key: NETWORK
        value: mainnet
      - key: NODE_ENV
        value: production
      - key: WALLET_SEED
        sync: false  # Set this in Render dashboard for security
